export const UPCOMING_MOVIE_REQUEST = 'UPCOMING_MOVIE_REQUEST';
export const UPCOMING_MOVIE_SUCCESS = 'UPCOMING_MOVIE_SUCCESS';
export const UPCOMING_MOVIE_ERROR = 'UPCOMING_MOVIE_ERROR';
export const UPCOMING_MOVIE_CLEAR = 'UPCOMING_MOVIE_CLEAR'

export const MOVIE_DETAIL_REQUEST = 'MOVIE_DETAIL_REQUEST';
export const MOVIE_DETAIL_SUCCESS = 'MOVIE_DETAIL_SUCCESS';
export const MOVIE_DETAIL_ERROR = 'MOVIE_DETAIL_ERROR';
export const MOVIE_DETAIL_CLEAR = 'MOVIE_DETAIL_CLEAR';

